
if [ "$TMUX" = "" ]; then tmux new-session -A -s main; fi

# The rendering of zellij is still not up to snuff
#
# if [[ -z "$ZELLIJ" ]] ; then
#   if [[ $(zellij ls 2>/dev/null |grep ^tiago$) = "tiago" ]]; then
#     zellij attach 'tiago'
#   else
#     zellij attach -c 'tiago'
#   fi
# fi

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
else
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k; 
fi

# Path additions
#
path+=("/usr/bin")
export PATH
export ZSH="$HOME/.oh-my-zsh"
# Install wmill CLI if not already installed
if ! command -v bat &> /dev/null; then
    alias bat='batcat'
fi
if ! command -v fd &> /dev/null; then
    alias fd='fdfind'
fi
if ! command -v exa &> /dev/null; then
    alias exa='eza'
fi
ZSH_THEME="powerlevel10k/powerlevel10k"

setopt auto_menu # automatically use menu completion
setopt always_to_end # move cursor to end if word had one match
zstyle ':completion:*' menu select # select completions with arrow keys
zstyle ':completion:*' group-name '' # group results by category
zstyle ':completion:::::' completer _expand _complete _ignored _approximate # enable approximate matches for completion
zstyle ":completion:*:git-checkout:*" sort false
zstyle ':completion:*:descriptions' format '[%d]'
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup
zstyle ':fzf-tab:complete:cd:*' popup-pad 200 0
zstyle ':fzf-tab:complete:cd:*' fzf-preview ' eza -1 --color=always $realpath'
zstyle :omz:plugins:ssh-agent lazy yes
zstyle :omz:plugins:ssh-agent quiet yes

# My Custom command completions

zstyle ':fzf-tab:complete:repos:*' fzf-preview 'bat --color=always --terminal-width=-20  ${UJ_DIR}/$realpath/README.md'
#repos() {
#    cd "${WHATEVER_DIR_WE_DEFINE}/$1"
#}
#_repos() {
#    # this is one way of defining completion by directory, where 
#    ((CURRENT == 2)) && _files -/ -W ${WHATEVER_DIR_WE_DEFINE}
#}
#compdef _repos repos

# Setting up zsh plugins
#
#
plugins=(git poetry virtualenv zsh-autosuggestions fzf-tab zsh-syntax-highlighting ssh-agent)
#Remember, for ssh to work as you like it you need to add the AddKeysToAgent on the ssh config
source $ZSH/oh-my-zsh.sh


source /usr/share/fzf/shell/key-bindings.zsh
# Default finder for fzf 
export FZF_DEFAULT_COMMAND="fd --type file --color=always"
export FZF_DEFAULT_OPTS="--ansi"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_CTRL_T_OPTS="--preview 'bat --color=always --line-range :500 {}'"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
enable-fzf-tab

export EDITOR="nvim"

nn() {
    if [[ -d "${1}" ]];
    then 
        cd "${1}"
    else
      cd "$(dirname "${1}")"
    fi
  nvim .
}

pn() {
  cd ${HOME}/Documents/personal
}

# Aliases

alias more='bat'
alias ls='eza'

# ls, the common ones I use a lot shortened for rapid fire usage
alias l='ls -lFh'     #size,show type,human readable
alias la='ls -laFh --icons'   #long list,show almost all,show type,human readable
alias lr='ls -tRFh'   #sorted by date,recursive,show type,human readable
alias lt='ls -ltFh'   #long list,sorted by date,show type,human readable

alias ll='ls -l'      #long list
alias ldot='ls -ld .*'
alias lS='ls -1FSsh'

alias lart='ls -1Fcart'
alias lrt='ls -1Fcrt'
alias lsr='ls -lARFh' #Recursive list of files and directories
alias lsn='ls -1'     #A column contains name of files and directories


tcow() {
    while tmux next-window 2> /dev/null; do
        tmux kill-window
    done
}

