[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#6e6a86"
blue = "#9ccfd8"
cyan = "#ebbcba"
green = "#31748f"
magenta = "#c4a7e7"
red = "#eb6f92"
white = "#e0def4"
yellow = "#f6c177"

[colors.dim]
black = "#6e6a86"
blue = "#9ccfd8"
cyan = "#ebbcba"
green = "#31748f"
magenta = "#c4a7e7"
red = "#eb6f92"
white = "#e0def4"
yellow = "#f6c177"

[colors.footer_bar]
background = "#1f1d2e"
foreground = "#e0def4"

[colors.hints.end]
background = "#1f1d2e"
foreground = "#6e6a86"

[colors.hints.start]
background = "#1f1d2e"
foreground = "#908caa"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "#26233a"
blue = "#9ccfd8"
cyan = "#ebbcba"
green = "#31748f"
magenta = "#c4a7e7"
red = "#eb6f92"
white = "#e0def4"
yellow = "#f6c177"

[colors.primary]
background = "#10111C"
bright_foreground = "#e0def4"
dim_foreground = "#908caa"
foreground = "#e0def4"

[colors.search.focused_match]
background = "#ebbcba"
foreground = "#191724"

[colors.search.matches]
background = "#26233a"
foreground = "#908caa"

[colors.selection]
background = "#403d52"
text = "#e0def4"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "IosevkaTiago Nerd Font"
style = "Medium"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B."
key = "Period"
mods = "Alt"

[[keyboard.bindings]]
chars = "#"
key = "Key3"
mods = "Alt"

[scrolling]
history = 5000

[window]
decorations = "full"
dynamic_padding = true
opacity = 1.0
option_as_alt = "OnlyLeft"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 2
y = 2
